# Generated by Django 4.1 on 2022-10-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0002_linklist_delete_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
